### PR TITLE
Update EaglercraftVersion.java

### PR DESCRIPTION
**Pull request by AR-DEV-1**
Do it 
For Lax1dude
For EaglerCraft
Pls Add me too

### CODE REVIEW

**Review by OtterCodes102 — CHANGES_REQUESTED** [review]
Plugins do not work in java, only javascript.

**Comment by OtterCodes102** [comment]
also NuraadGit made the repo that i imported the eagler source code from, not buildtools.

**Comment by ZXMushroom63** [comment]
Is it ok to change lax1dude's signature everywhere? I mean, he made the majority of this project.

**Comment by ZXMushroom63** [comment]
also, your launcher might not work because TeaVM dos not support Swing
https://teavm.org/jcl-report/recent/jcl.html

**Comment by ZXMushroom63** [comment]
Also, for the plugins in java, you are using `net.minecraftforge.fml`.
Are you going to port forge?

**Comment by AR-DEV-1** [comment]
> Also, for the plugins in java, you are using `net.minecraftforge.fml`. Are you going to port forge?

Yes I will port Forge 
I am also working on the Marketplace

**Pull request closed without merging**
