### PR TITLE
Initial implementation of the Mod API

### PR DESCRIPTION
**Pull request by ZXMushroom63**
Hello!

This is the PR mentioned in #52, which implements the following features:

- `PluginAPI` JavaScript object
- The `net.zxmushroom63.plugins` package.
- The plugin loader backend.
- The plugin loader GUI: Main Menu -> Options -> Plugins
- The `BaseData` and `PluginData` classes which allow Java and JavaScript to communicate
- The `updateComponent` system
- The `makePluginData` function in `Entity.java` which parses itself in to a `PluginData`.

The plugin api still needs a few things, such as:
- Moving some code from onUpdate in EntityPlayerSP.java to PluginAPI.java
- Finishing `Entity.java`'s `makePluginData`
- makePluginData for a lot of classes
- other globals (`PluginAPI.player`, `PluginAPI.world`)

### CODE REVIEW

**Comment by ZXMushroom63** [comment]
Edit: just found that I introduced a severe bug.
I'll re-open the PR when it's fixed.

**Comment by OtterCodes101** [comment]
i'll just make it a draft PR.

**Comment by OtterCodes101** [comment]
also just resolved a merge conflict.

**Comment by ZXMushroom63** [comment]
thanks for that!

Either way, I think I figured out what the bug is. Still needs a bit more testing though.

I'm blaming the `fishEntity` in `EntityPlayerSP.java` being null, causing makePluginData to fail.

**Comment by Orphanlol** [comment]
Nice API
real moment
will this really work

**Comment by OtterCodes101** [comment]
> will this really work

alr does

**Comment by ZXMushroom63** [comment]
> Nice API real moment will this really work

Well, I've made 2 example plugins which do work. Currently functionality is limited, as you have to manually expose variables and functions, but it can be easily expanded.

**Comment by jitdummy** [comment]
do yall have any current servers? i would like 2 join

**Comment by ZXMushroom63** [comment]
Just implemented FishHookData so I can make a grappling hook mod, and it works!

I can assure you that I'll be spending a lot of time playing with it!

**Comment by OtterCodes101** [comment]
should i merge now?

**Review by OtterCodes101 — CHANGES_REQUESTED** [review]
Please move plugin documentation to the eaglerreborn.github.io repository.

**Comment by OtterCodes101** [comment]
also,
```
[TeaVMBridge] Encountered 8 problems while building:
[TeaVMBridge]     - ERROR: class org.teavm.diagnostics.Problem : org.teavm.model.CallLocation@88e0ff3e - Error in @JSBody script line 0, char 30: missing formal parameter - params: [ ]
[TeaVMBridge]     - ERROR: class org.teavm.diagnostics.Problem : org.teavm.model.CallLocation@88e0ff3e - Error in @JSBody script line 5, char 51: missing ) after argument list - params: [ ]
[TeaVMBridge]     - ERROR: class org.teavm.diagnostics.Problem : org.teavm.model.CallLocation@88e0ff3e - Error in @JSBody script line 5, char 51: missing ) after argument list - params: [ ]
[TeaVMBridge]     - ERROR: class org.teavm.diagnostics.Problem : org.teavm.model.CallLocation@88e0ff3e - Error in @JSBody script line 5, char 51: missing ; before statement - params: [ ]
[TeaVMBridge]     - ERROR: class org.teavm.diagnostics.Problem : org.teavm.model.CallLocation@88e0ff3e - Error in @JSBody script line 5, char 63: missing ; before statement - params: [ ]
[TeaVMBridge]     - ERROR: class org.teavm.diagnostics.Problem : org.teavm.model.CallLocation@88e0ff3e - Error in @JSBody script line 5, char 63: syntax error - params: [ ]
[TeaVMBridge]     - ERROR: class org.teavm.diagnostics.Problem : org.teavm.model.CallLocation@88e0ff3e - Error in @JSBody script line 5, char 71: missing ; before statement - params: [ ]
[TeaVMBridge]     - ERROR: class org.teavm.diagnostics.Problem : org.teavm.model.CallLocation@88e0ff3e - Error in @JSBody script line 5, char 71: syntax error - params: [ ]
```

**Comment by ZXMushroom63** [comment]
Right made a PR for EaglerReborn.github.io

**Comment by ZXMushroom63** [comment]
As for the errors, I can't replicate them.

Were you compiling it from the workspace or from the GUI?

**Comment by ZXMushroom63** [comment]
Right, I managed to replicate the errors.

They only seem to occur when not using the workspace. Still at a loss as to why they happen.

**Review by OtterCodes101 — APPROVED** [review]

**Comment by OtterCodes101** [comment]
> Right, I managed to replicate the errors.
> 
> They only seem to occur when not using the workspace. Still at a loss as to why they happen.

prob smthing with teavmbridge

**Comment by ZXMushroom63** [comment]
Well, I think if I throw away most of the error logs and just keep this: `Error in @JSBody script`, I can figure out that one of my scripts is broken.

Also found that when I removed the linebreaks from all scripts, the error log reported `Error in @JSBody script line 0`, and before it reported `Error in @JSBody script line 14`.

Just a matter of time before I figure it out then, since all I need to do is add back my line breaks one by one till I find the problem.

**Comment by ZXMushroom63** [comment]
Right, I patched the problems. It apears that TeaVMBridge hates a lot of things, like assigning functions to variables, and async/await.

I have to refactor a lot of my code to make it work exactly how TeaVM wants it to, but, I think it works now! Just need to test some stuff.

**Comment by ZXMushroom63** [comment]
OK! Fixed the errors! The mod api is ready for merging!

**Pull request merged**
