### PR TITLE
made a new title

### PR DESCRIPTION
**Pull request by radmanplays**

### CODE REVIEW

**Comment by radmanplays** [comment]
i made a new title and i added a way to compile the latest client with no ui but only for windows bc i dont know how to do it for linux too

**Comment by radmanplays** [comment]
it took me 1-2 hours to make them so please merge this pull request

**Comment by OtterCodes101** [comment]
> i added a way to compile the latest client with no ui

You can do that, even if the script names are cryptic

**Comment by OtterCodes101** [comment]
also no thank you on the new title, this would require me to do a whole rebrand

**Pull request closed without merging**
